### ISSUE TITLE
Cannot download video

### ISSUE THREAD

**Issue by Ten1o** [easychen/tumblr-like-exporter#12]
Having used
`php robo.phar export video` and 
`php robo.phar download `. 
However, videos can only be found in "export video" steps, rather than "download" step. Only pics are downloaded, no videos are downloaded.

**Comment by easychen** [comment]
Download process won't care whether image or video , it  just save the  link . 
Is there any curl error when downloading video ? 

Or you can post a video url here  i will try to reproduce and debug

**Comment by Ten1o** [comment]
Problem solved after switching to another network, thanks a lot.
