### ISSUE TITLE
Mac提示curl: (7) Failed to connect to www.tumblr.com port 443: Operation timed out

### ISSUE THREAD

**Issue by ChenCody** [easychen/tumblr-like-exporter#3]
Mac环境执行php robo.phar export会提示
`curl: (7) Failed to connect to www.tumblr.com port 443: Operation timed out`
本地chrome可以访问tumblr，已翻墙

**Comment by easychen** [comment]
命令行需要额外加代理。你直接 curl tumblr 应该也是这个错。
