### ISSUE TITLE
[Feature]没有断点记录

### ISSUE THREAD

**Issue by CodeEagle** [easychen/tumblr-like-exporter#4]
因为代理环境不稳定，常常访问4-5个页面就会断开，重新开始又从1开始，永远 loop 不完

**Comment by easychen** [comment]
> 因为代理环境不稳定，常常访问4-5个页面就会断开，重新开始又从1开始，永远 loop 不完

本身就是有断点支持的，页面是每个一个断点，下载是10张图片一个断点。第二次运行时最开始会提示是否继续上次的页面，选Y就好。
