### ISSUE TITLE
curl: (56) Unexpected EOF

### ISSUE THREAD

**Issue by xorxorxorxor** [easychen/tumblr-like-exporter#5]
I encountered this issuse when i entered the following command:
`proxychains php robo.phar export`
the response:
```
ProxyChains-3.1 (http://proxychains.sf.net)
?  Please enter tumblr username( which show in url like https://www.tumblr.com/blog/username ) who's like to download , for yourslef's like just press enter : 
➜  download and parse page https://www.tumblr.com/likes 🔍 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0|DNS-request| www.tumblr.com 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| www.tumblr.com is 119.161.5.26
|S-chain|-<>-127.0.0.1:1080-<><>-119.161.5.26:443-<><>-OK
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Unexpected EOF
➜  image url saved... 🖼 
```
this is my php version:
`PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
`

**Comment by hucheng91** [comment]
i think you need cookie

**Comment by hucheng91** [comment]
@xorxorxorxor  i think you need cookie

**Comment by easychen** [comment]
It seems network problem ,  i don't know how to work with ProxyChains , but if you are using shadowsocks   copy and paste the shell should work.
![image](https://user-images.githubusercontent.com/1294760/49486830-ed8dec80-f87a-11e8-861b-f2afa279ea71.png)
