### ISSUE TITLE
curl: (3) Illegal characters found in URL

### ISSUE THREAD

**Issue by felixmon** [easychen/tumblr-like-exporter#6]
Hi there!

My scripts are these:

$ vim next.txt // i write : https://somename.tumblr.com
$ php robo.phar export

then then terminal returns this error:

curl: (3) Illegal characters found in URL

I googled the problem, maybe it's something wrong with the URL that "curl" gets?

Thank you for your reply.

**Comment by easychen** [comment]
use this url :
`https://www.tumblr.com/blog/somename`

notice that `somename` must be one of YOUR blog .

**Comment by zzzop** [comment]
相同的错误提示，但是我网址填对了呀，是因为cookie吗？
![2018-12-07 103930](https://user-images.githubusercontent.com/28821632/49624717-87859e80-fa0d-11e8-96ca-d06d42972b6e.jpg)



> php robo.phar export
?  found https://www.tumblr.com/blog/modomoduo
 , continue ?  [Y] 
➜  download and parse page https://www.tumblr.com/blog/modomoduo
 🔍 
curl: (3) Illegal characters found in URL
➜  image url saved... 🖼 

下载like里面的话就是什么都不提示

> php robo.phar export
?  Please enter tumblr username( which show in url like https://www.tumblr.com/blog/username ) who's like to download , for yourslef's like just press enter : 
?  download and parse page https://www.tumblr.com/likes ?? 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
?  image url saved... ??
