### ISSUE TITLE
能不能批量爬取

### ISSUE THREAD

**Issue by Leslie-Luo** [easychen/tumblr-like-exporter#7]
大佬能不能在next.txt填写多个地址，批量爬取内容

**Comment by easychen** [comment]
不能，如果你不怕被ban的话，可以：

1：把这个值改为0，取消等待时间
https://github.com/easychen/tumblr-like-exporter/blob/master/RoboFile.php#L14

2：直接复制整个目录，新开一个终端，把新网址填进去。不过还不够，可以再复制一个。
