### ISSUE TITLE
显示保存图片地址了，打开文件里面是空的，怎么解决呢？

### ISSUE THREAD

**Issue by helloqingfeng** [easychen/tumblr-like-exporter#9]
![360 20181207002535826](https://user-images.githubusercontent.com/9712785/49597147-c89e9400-f9b6-11e8-915d-afac4aadf6ed.jpg)

images.json文件里面是空的，没有任何地址，终端也翻墙了，不知道哪里出问题了
![360 20181207002657131](https://user-images.githubusercontent.com/9712785/49597303-1c10e200-f9b7-11e8-8e2f-a84eca8b2c73.jpg)

![360 20181207002827912](https://user-images.githubusercontent.com/9712785/49597291-14e9d400-f9b7-11e8-949a-034f5547a345.jpg)

**Comment by easychen** [comment]
你使用的 curl 命令不支持 https …
